Connected to Python 3.14.2

In [ ]:
import numpy as np

STUDENT_NAME = "Robert Gabriel A. Gamas"
STUDENT_ID = 20250925

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)

print("Mean:", mean_val, "Std Dev:", std_val)   

Robert Gabriel A. Gamas's Array: [26 36 72 66 58 45  7 37 11 65]
Mean: 42.3 Std Dev: 21.845136758555665


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
print(f"{STUDENT_NAME}'s Matrix:\n", matrix) 
 
row_sums = np.sum(matrix, axis=1) 
col_sums = np.sum(matrix, axis=0) 
print("Row sums:", row_sums) 
print("Column sums:", col_sums)

Robert Gabriel A. Gamas's Matrix:
 [[26 33 36  8]
 [ 2 33  7 16]
 [37 11  1 25]]
Row sums: [103  58  74]
Column sums: [65 77 44 49]


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3)) 
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d) 
 
slice_mid = arr3d[:,1,:] 
print("Slice[:,1,:]:\n", slice_mid) 

Robert Gabriel A. Gamas's 3D Array:
 [[[ 9  0  3]
  [ 7  1  9]
  [12  0  6]]

 [[ 4 10  0]
  [12 14  8]
  [ 4  7  0]]

 [[ 1  1  3]
  [ 6  4  6]
  [ 2 11 12]]]
Slice[:,1,:]:
 [[ 7  1  9]
 [12 14  8]
 [ 6  4  6]]


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)] 
print(f"{STUDENT_NAME}'s Original:", x) 
print("Filtered subset:", filtered) 

Robert Gabriel A. Gamas's Original: [26 36 72 66 58 45  7 37 11 65]
Filtered subset: []


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925
 
np.random.seed(STUDENT_ID) 
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
print("Matrix A:\n", A) 
print("Matrix B:\n", B) 
 
product = A @ B 
det_A = np.linalg.det(A) 
print("A @ B:\n", product) 
print("Determinant of A:", det_A)

Matrix A:
 [[26 33]
 [36  8]]
Matrix B:
 [[ 2 33]
 [ 7 16]]
A @ B:
 [[ 283 1386]
 [ 128 1316]]
Determinant of A: -979.9999999999998


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
angles = np.linspace(0, 2*np.pi, 8) 
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles) 
print(f"{STUDENT_NAME}'s Angles:", angles) 
print("Sine:", sine_vals) 
print("Cosine:", cos_vals)

Robert Gabriel A. Gamas's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4)) 
arr[::2, ::2] = 0 
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Robert Gabriel A. Gamas's Modified 4x4 Array:
 [[ 0 33  0  8]
 [ 2 33  7 16]
 [ 0 11  0 25]
 [ 5 33 34 18]]


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925
 
np.random.seed(STUDENT_ID) 
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10) 
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail') 
print(f"{STUDENT_NAME}'s Scores:", scores) 
print("Grades:", grades) 

Robert Gabriel A. Gamas's Scores: [25 35 71 65 57 44  6 36 10 64]
Grades: ['Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail']


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
flat_arr = arr.flatten() 
transposed_arr = arr.T 
print("Original array:\n", arr) 
print("Flattened:", flat_arr) 
print("Transposed:\n", transposed_arr)

Original array:
 [[26 33 36  8]
 [ 2 33  7 16]
 [37 11  1 25]]
Flattened: [26 33 36  8  2 33  7 16 37 11  1 25]
Transposed:
 [[26  2 37]
 [33 33 11]
 [36  7  1]
 [ 8 16 25]]


In [ ]:
import numpy as np 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3)) 
mask = arr % 2 == 0 
arr[mask] = -1 
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 33 -1]
 [-1 -1 33]
 [ 7 -1 37]]


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
STUDENT_ID%100+50,5), 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
print(df)

                      Name  Score  YearsCodePro
0  Robert Gabriel A. Gamas     50             9
1  Robert Gabriel A. Gamas     57            12
2  Robert Gabriel A. Gamas     60             0
3  Robert Gabriel A. Gamas     32             6
4  Robert Gabriel A. Gamas     26             4


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'], 
    # Corrected to use a functional salary range, e.g., 40000 to 150000 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean() 
print(avg_salary)

EdLevel
Bachelor    110640.0
Master      115536.5
PhD          95971.0
Name: ConvertedComp, dtype: float64


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
top5 = df.sort_values(by='ConvertedComp', ascending=False) 
print(top5)

       Country  ConvertedComp
4      Germany         126081
0  Philippines         123481
1          USA         104992
3       Canada          97799
2           UK          95971


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name':[STUDENT_NAME]*5, 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
high_exp = df[df['YearsCodePro']>STUDENT_ID%10] 
print(high_exp)

                      Name  YearsCodePro
0  Robert Gabriel A. Gamas             9
3  Robert Gabriel A. Gamas             7


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
bins = [0, 50000, 100000, 150000, 200000] 
labels = ['0-50k', '50-100k', '100-150k', '>150k'] 
 
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels) 
print(df)

   ConvertedComp   Bracket
0         123481  100-150k
1         104992  100-150k
2          95971   50-100k
3          97799   50-100k
4         126081  100-150k


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
# Original Code Issue:  
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)  
# -> np.random.randint(12345, 12345, 5) which is a zero-length range. 
 
# Corrected Code: Using a functional salary range (40000 to 150000) 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
df['LogComp'] = np.log(df['ConvertedComp']) 
print(df)

   ConvertedComp    LogComp
0         123481  11.723843
1         104992  11.561639
2          95971  11.471801
3          97799  11.490670
4         126081  11.744680


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5), 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
corr_matrix = df.corr() 
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.292614
ConvertedComp     -0.292614       1.000000


In [2]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
# Calculate mean, median, and standard deviation for each 'EdLevel' 
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index() 
print(summary)

    EdLevel      mean    median           std
0  Bachelor  110640.0  110640.0  18159.916354
1    Master  115536.5  115536.5  14912.174908
2       PhD   95971.0   95971.0           NaN


In [1]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
# Generate salaries: [100727, 136195, 130612, 100727, 95233] 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
threshold = 110000 
 
# Create the 'HighPay' column using np.where() 
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No') 
 
print(df)

   ConvertedComp HighPay
0         123481     Yes
1         104992      No
2          95971      No
3          97799      No
4         126081     Yes


In [ ]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Robert Gabriel A. Gamas" 
STUDENT_ID = 20250925 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5) 
}) 
 
# Group by 'Country' and calculate the mean and max 'ConvertedComp' 
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max']) 
print(top_countries)

                 mean     max
Country                      
Canada        97799.0   97799
Germany      126081.0  126081
Philippines  123481.0  123481
UK            95971.0   95971
USA          104992.0  104992
